// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:123456789:web:demo',
    messagingSenderId: '123456789',
    projectId: 'falla-demo',
    authDomain: 'falla-demo.firebaseapp.com',
    storageBucket: 'falla-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS-1WcDKAeoyNdzbLCTBM8R6Yo3DWADMQ',
    appId: '1:916591463999:android:938b82de32ffbe12c1328a',
    messagingSenderId: '916591463999',
    projectId: 'falla-6b4f1',
    storageBucket: 'falla-6b4f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB85hIkHBrX_k9_tkBxVyr_FgEAmUlsOfw',
    appId: '1:916591463999:ios:43af0ea7e53ddf88c1328a',
    messagingSenderId: '916591463999',
    projectId: 'falla-6b4f1',
    storageBucket: 'falla-6b4f1.firebasestorage.app',
    iosBundleId: 'com.mustafakarakus.falla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB85hIkHBrX_k9_tkBxVyr_FgEAmUlsOfw',
    appId: '1:916591463999:ios:43af0ea7e53ddf88c1328a',
    messagingSenderId: '916591463999',
    projectId: 'falla-6b4f1',
    storageBucket: 'falla-6b4f1.firebasestorage.app',
    iosBundleId: 'com.mustafakarakus.falla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:123456789:web:demo',
    messagingSenderId: '123456789',
    projectId: 'falla-demo',
    authDomain: 'falla-demo.firebaseapp.com',
    storageBucket: 'falla-demo.appspot.com',
  );
}
